package ma.luan.yiyan.util;


import io.vertx.core.Future;
import io.vertx.core.buffer.Buffer;
import java.util.Base64;

import java.io.IOException;

public class ConvertUtil {
    /**
     * @param obj base64 加密后的图片
     * @return Buffer 流
     */
    public static Future<Buffer> getImageFromBase64(String obj) {
        Future<Buffer> result = Future.future();
        if (obj == null) {
            result.fail("图片读取失败");
            return result;
        }

        Base64.Decoder decoder = Base64.getDecoder();
        byte[] bs;
        bs = decoder.decode(obj);
        Buffer buffer = Buffer.buffer(bs);
        result.complete(buffer);
        return result;
    }

    private static final String svgTemplate =
        "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"22\" width = \"%.2f\">\n" +
            "    <!-- Generated by https://api.gushi.ci/ -->\n" +
            "    <g>\n" +
            "        <text  text-anchor=\"start\" letter-spacing = \"1.5px\" font-smoothing = \"antialiased\" font-family='KaiTi, \"Segoe UI\", \"Lucida Grande\", Helvetica, Arial, \"Microsoft YaHei\", FreeSans, Arimo, \"Droid Sans\",\"wenquanyi micro hei\",\"Hiragino Sans GB\", \"Hiragino Sans GB W3\", sans-serif' font-size=\"20\" id=\"svg_1\" y=\"20\" x=\"0\" stroke-width=\"0\" stroke=\"#000\" fill=\"#000000\">%s</text>\n" +
            "    </g>\n" +
            "</svg>";

    public static String getSvg(String content) {
        return String.format(svgTemplate,content.length()*20+(content.length()-1)*1.5, content);
    }
}
